[build]
command = "npm run build"
publish = "public/"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../plugin/"

[[plugins]]
package = "../plugin"

[[plugins]]
package = "@netlify/plugin-local-install-core"