[build]
command = "npm run build"
publish = "public/"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF .."

[[plugins]]
package = "../plugin/src/index.ts"

[[plugins]]
package = "@netlify/plugin-local-install-core"
