name: Plugin Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
      - name: Global Node packages cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key:
            ubuntu--build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
      - name: Test fixture dependency cache
        uses: actions/cache@v3
        with:
          path: plugin/test/fixtures/**/node_modules
          key:
            ubuntu-build-${{ env.cache-name }}-${{
            hashFiles('plugin/test/fixtures/**/package.json') }}-node-modules
      - run: npm install -g netlify-cli
      - run: npm ci
      - run: cd plugin && npm ci && npm run build
      - run: npm test

  build-mac:
    runs-on: macOS-latest
    needs: build-ubuntu
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
      - name: Global Node packages cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key:
            macOS-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
      - name: Test fixture dependency cache
        uses: actions/cache@v3
        with:
          path: plugin/test/fixtures/**/node_modules
          key:
            macOS-build-${{ env.cache-name }}-${{
            hashFiles('plugin/test/fixtures/**/package.json') }}-node-modules
      - run: npm install -g netlify-cli
      - run: npm ci
      - run: cd plugin && npm ci && npm run build
      - run: npm test
